# 数値解析2020 レポート


**X-B.**


以下Python3を用いたプログラム例を示す。

In [ ]:
# Pythonのバージョン確認
import sys
print(sys.version)

3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]


# 解答コード

In [ ]:
import numpy as np

n = 8

h = np.array([111, 155, 146, 85, 216, 330, 225, 214])
a = np.array([112, 193, 104, 29, 237, 190, 210, 300])
d = np.array([ 96, 151, 114, 85, 186, 169, 210, 182])

h_ave = 0
a_ave = 0
d_ave = 0
for i in range(n):
    h_ave += h[i]
    a_ave += a[i]
    d_ave += d[i]
h_ave = h_ave / n
a_ave = a_ave / n
d_ave = d_ave / n

s_h = 0
s_a = 0
s_d = 0
for i in range(n):
    s_h += h[i]**2
    s_a += a[i]**2
    s_d += d[i]**2
s_h = np.sqrt((s_h - n*h_ave**2) / (n-1))
s_a = np.sqrt((s_a - n*a_ave**2) / (n-1))
s_d = np.sqrt((s_d - n*d_ave**2) / (n-1))

In [ ]:
H = np.zeros(n)
A = np.zeros(n)
D = np.zeros(n)

for i in range(n):
    H[i] = (h[i] - h_ave)/s_h
    A[i] = (a[i] - a_ave)/s_a
    D[i] = (d[i] - d_ave)/s_d

print(H)
print(A)
print(D)

[-0.95489296 -0.38903046 -0.50477507 -1.28926625  0.39546072  1.861559
  0.51120532  0.3697397 ]
[-0.69811892  0.24630918 -0.79139577 -1.66586624  0.75933186  0.21133036
  0.44452249  1.49388705]
[-1.1587752   0.04089795 -0.76615489 -1.39870982  0.80432631  0.43351825
  1.32782005  0.71707736]


In [ ]:
y_1 = np.array([0.54847651, 0.57878772, 0.60347186])
y_2 = np.array([-0.80399165, 0.5633186, 0.19044575])
y_3 = np.array([-0.22971926, -0.58964136, 0.77430752])


PC1 = np.zeros(n)
PC2 = np.zeros(n)
PC3 = np.zeros(n)

for i in range(n):
    PC1[i] = y_1[0] * H[i] + y_1[1] * A[i] + y_1[2] * D[i]
    PC2[i] = y_2[0] * H[i] + y_2[1] * A[i] + y_2[2] * D[i]
    PC3[i] = y_3[0] * H[i] + y_3[1] * A[i] + y_3[2] * D[i]

print(PC1)
print(PC2)
print(PC3)

In [ ]:
params = 3
y_1 = np.array([0.54847651, 0.57878772, 0.60347186])
y_2 = np.array([-0.80399165, 0.5633186, 0.19044575])
y_3 = np.array([-0.22971926, -0.58964136, 0.77430752])

r = np.zeros(n * params)
r = r.reshape(n, params)

for i in range(n):
    r[i][0] = H[i]
    r[i][1] = A[i]
    r[i][2] = D[i]

PC1 = np.zeros(n)
PC2 = np.zeros(n)
PC3 = np.zeros(n)

for i in range(n):
    for j in range(params):
        PC1[i] += y_1[j] * r[i][j]
        PC2[i] += y_2[j] * r[i][j]
        PC3[i] += y_3[j] * r[i][j]

print(PC1)
print(PC2)
print(PC3)

[[-0.95489296 -0.69811892 -1.1587752 ]
 [-0.38903046  0.24630918  0.04089795]
 [-0.50477507 -0.79139577 -0.76615489]
 [-1.28926625 -1.66586624 -1.39870982]
 [ 0.39546072  0.75933186  0.80432631]
 [ 1.861559    0.21133036  0.43351825]
 [ 0.51120532  0.44452249  1.32782005]
 [ 0.3697397   1.49388705  0.71707736]]
[-1.62708724 -0.04613258 -1.19726034 -2.5153972   1.14178117  1.40495287
  1.3389703   1.50017302]
[ 0.15377878  0.45931663 -0.18588397 -0.16823248  0.26297917 -1.29506986
  0.09228066  0.68083107]
[-0.26625125 -0.0241987  -0.01064326  0.19540139  0.0842175  -0.21656864
  0.6485985  -0.41055553]


In [ ]:
params = 3
y_1 = np.array([0.54847651, 0.57878772, 0.60347186])
y_2 = np.array([-0.80399165, 0.5633186, 0.19044575])
y_3 = np.array([-0.22971926, -0.58964136, 0.77430752])

r = np.zeros(n * params)
r = r.reshape(n, params)

for i in range(n):
    r[i][0] = H[i]
    r[i][1] = A[i]
    r[i][2] = D[i]

PC1 = np.zeros(n)
PC2 = np.zeros(n)
PC3 = np.zeros(n)

for i in range(n):
    PC1[i] = np.dot(y_1, r[i])
    PC2[i] = np.dot(y_2, r[i])
    PC3[i] = np.dot(y_3, r[i])

print(PC1)
print(PC2)
print(PC3)

[-1.62708724 -0.04613258 -1.19726034 -2.5153972   1.14178117  1.40495287
  1.3389703   1.50017302]
[ 0.15377878  0.45931663 -0.18588397 -0.16823248  0.26297917 -1.29506986
  0.09228066  0.68083107]
[-0.26625125 -0.0241987  -0.01064326  0.19540139  0.0842175  -0.21656864
  0.6485985  -0.41055553]
